name: test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CALLRAIL_API_KEY: ${{ secrets.CALLRAIL_API_KEY }}
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.x']
      
    name: pytest ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        python -m pip install -e .[test]
      
    - name: Run tests
      shell: bash
      run: |
        pytest -vs --cov=pycallrail --cov-report term-missing:skip-covered

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3